--INSERT INTO cliente (id, correo, identificacion, nombre, numero_celular, tipo_identificacion) VALUES (1, 'peramon@utpl.edu.ec','15224662481001','Julio Casas','05547851201','RUC');
--INSERT INTO direccion (id,provincia,ciudad,direccion, cd_fk) VALUES (1,'LOJA','LOJA','SAN AGUSTIN',1);
--INSERT INTO direccion (id,provincia,ciudad,direccion, cd_fk) VALUES (2,'ZAMORA','ZAMORA','AV. DEL MAESTRO',1);